config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get '/inicio', to: 'welcome#index'
  resources :citizens

  root to: 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/citizen.rb
class Citizen < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/citizens_controller.rb
class CitizensController < ApplicationController
  before_action :set_citizen, only: %i[ show edit update destroy ]

  # GET /citizens or /citizens.json
  def index
    @citizens = Citizen.all
  end

  # GET /citizens/1 or /citizens/1.json
  def show
  end

  # GET /citizens/new
  def new
    @citizen = Citizen.new
  end

  # GET /citizens/1/edit
  def edit
  end

  # POST /citizens or /citizens.json
  def create
    @citizen = Citizen.new(citizen_params)

    respond_to do |format|
      if @citizen.save
        format.html { redirect_to citizen_url(@citizen), notice: "Citizen was successfully created." }
        format.json { render :show, status: :created, location: @citizen }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @citizen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /citizens/1 or /citizens/1.json
  def update
    respond_to do |format|
      if @citizen.update(citizen_params)
        format.html { redirect_to citizen_url(@citizen), notice: "Citizen was successfully updated." }
        format.json { render :show, status: :ok, location: @citizen }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @citizen.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /citizens/1 or /citizens/1.json
  def destroy
    @citizen.destroy

    respond_to do |format|
      format.html { redirect_to citizens_url, notice: "Citizen was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_citizen
      @citizen = Citizen.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def citizen_params
      params.require(:citizen).permit(:first_name, :last_name, :cpf, :cns, :email, :birthday, :phone, :photo, :status)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/citizens_helper.rb
module CitizensHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/citizens/_form.html.erb
<%= form_with(model: citizen, local: true) do |form| %>
  <% if citizen.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(citizen.errors.count, "error") %> prohibited this citizen from being saved:</h2>

      <ul>
      <% citizen.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :cpf %>
    <%= form.text_field :cpf %>
  </div>

  <div class="field">
    <%= form.label :cns %>
    <%= form.text_field :cns %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :birthday %>
    <%= form.text_field :birthday %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.text_field :photo %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/citizens/edit.html.erb
<h1>Editing Citizen</h1>

<%= render 'form', citizen: @citizen %>

<%= link_to 'Show', @citizen %> |
<%= link_to 'Back', citizens_path %>

app/views/citizens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Citizens</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Cpf</th>
      <th>Cns</th>
      <th>Email</th>
      <th>Birthday</th>
      <th>Phone</th>
      <th>Photo</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @citizens.each do |citizen| %>
      <tr>
        <td><%= citizen.first_name %></td>
        <td><%= citizen.last_name %></td>
        <td><%= citizen.cpf %></td>
        <td><%= citizen.cns %></td>
        <td><%= citizen.email %></td>
        <td><%= citizen.birthday %></td>
        <td><%= citizen.phone %></td>
        <td><%= citizen.photo %></td>
        <td><%= citizen.status %></td>
        <td><%= link_to 'Show', citizen %></td>
        <td><%= link_to 'Edit', edit_citizen_path(citizen) %></td>
        <td><%= link_to 'Destroy', citizen, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Citizen', new_citizen_path %>

app/views/citizens/new.html.erb
<h1>New Citizen</h1>

<%= render 'form', citizen: @citizen %>

<%= link_to 'Back', citizens_path %>

app/views/citizens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @citizen.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @citizen.last_name %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @citizen.cpf %>
</p>

<p>
  <strong>Cns:</strong>
  <%= @citizen.cns %>
</p>

<p>
  <strong>Email:</strong>
  <%= @citizen.email %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @citizen.birthday %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @citizen.phone %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @citizen.photo %>
</p>

<p>
  <strong>Status:</strong>
  <%= @citizen.status %>
</p>

<%= link_to 'Edit', edit_citizen_path(@citizen) %> |
<%= link_to 'Back', citizens_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Challenger24</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Seja bem vindo</h1>
<ul>
    <li>
        <%= link_to "Cadastro de munícipes", citizens_path%>
    </li>
</ul>